### ISSUE TITLE
Patch to fix typo in help output

### ISSUE THREAD

**Issue by pronovic** [vapier/ncompress#1]
Below is patch code-typos.patch from Debian package 4.2.4.4-10.  It fixes a minor typo in the help output.   

KEN

```
# Description: Fix typos in the code.
# Author: Kenneth J. Pronovici <pronovic@debian.org>
Index: ncompress-4.2.4.4/compress42.c
===================================================================
--- ncompress-4.2.4.4.orig/compress42.c
+++ ncompress-4.2.4.4/compress42.c
@@ -877,7 +877,7 @@ Usage: %s [-dfvcVr] [-b maxbits] [file .
             If -f is not used, the user will be prompted if stdin is.\n\
             a tty, otherwise, the output file will not be overwritten.\n\
        -v   Write compression statistics.\n\
-       -V   Output vesion and compile options.\n\
+       -V   Output version and compile options.\n\
        -r   Recursive. If a filename is a directory, descend\n\
             into it and compress everything in it.\n");
```

**Comment by vapier** [comment]
can you please send these as pull requests instead of pasting them inline ?

**Comment by pronovic** [comment]
Sorry, it wasn't entirely obvious the best way to provide patches.  Github doesn't allow attachments.  I haven't done a pull request before, but I'm sure I can figure it out.  I'll try to do it this weekend, otherwise it will be sometime next week.

**Comment by pronovic** [comment]
This patch is not included in the pull request referenced above.  It looks like it's already been applied (not sure when).

**Comment by vapier** [comment]
see commit 148da0e0dcb7ff7833d4f9b2cd60cf0c8f6759b7
