### ISSUE TITLE
The error "filename too long to tack on .Z"

### ISSUE THREAD

**Issue by praiskup** [vapier/ncompress#12]
https://github.com/vapier/ncompress/blob/4e663b112481344684d55768361d3b36517c3154/compress42.c#L1037

Can anyone please explain to me why that `if ()` block is needed?  I'm considering to fill a PR which will drop that entirely.  Any objections?

**Comment by vapier** [comment]
the check is for old DOS/Windows systems with [8.3 filename limitations](https://en.wikipedia.org/wiki/8.3_filename).  on those systems, the check is necessary, but i don't think we need to care about them anymore.  if anyone is still running such a system, they can patch the code themselves, or use a distro like [FreeDOS](https://www.freedos.org) to get compress support.
