### ISSUE TITLE
question: what is the difference between `master` and `ncompress-4.2.4` branch?

### ISSUE THREAD

**Issue by praiskup** [vapier/ncompress#13]
ssia

**Comment by vapier** [comment]
i thought i mentioned this somewhere.  the homepage alludes to it.

the 4.2.4 branch is basically bugfixes only based on the last release not made by me.
the master branch is about modernizing the codebase while still being input/output compatible.

i can add an explicit note to the README.md file.

**Comment by praiskup** [comment]
I'd say that 'master' branch should be the primary branch here on github
then.

I plan to submit some leak fixes; so per homepage, I should submit two pull
requests (since that's bugfix).

Btw., when do you plan to release 4.2.5+?

**Comment by vapier** [comment]
i would only worry about the 4.2.4 branch.  i'm not going to promote master/4.2.5 until it's in a much better shape and that's going to take more dev time.

**Comment by praiskup** [comment]
Thanks.
