### ISSUE TITLE
[Windows Compilation] Consider adding preprocessor macro for lstat and chown

### ISSUE THREAD

**Issue by deguich** [vapier/ncompress#18]
I just add this to compress.c to enable compilation on Windows :

```
#ifndef _WIN32
	if (chown(ofname, infstat.st_uid, infstat.st_gid)) { /* Copy ownership */
		fprintf(stderr, "\nchown error (ignored) ");
		perror(ofname);
		exit_code = 1;
	}
#endif
```

```
#ifndef _WIN32
	signal(SIGHUP, (SIG_TYPE)abort_compress);
#endif
```

_2 times (line 453 and 465)_ :

```
#ifdef _WIN32
	if (stat(tempname, &infstat) == -1) {
#else
	if (lstat(tempname, &infstat) == -1) {
#endif
```

I added this symbol at compilation time :
- BYTE_ORDER=LITTLE_ENDIAN

I updated makefile too ; patchlevel.h cannot be created with this command on Windows : 
```
patchlevel.h: version
	echo "#define VERSION \"`cat version`\"" > patchlevel.h
```

And ... **It works**

**Comment by vapier** [comment]
i've improved the signal logic in commit 18a23ab5bb54624a8be94d277ca3e0ebf5b50cb8.

the code doesn't use `BYTE_ORDER` or other endian defines so i don't see why Windows would care about them.  you'd have to provide more info there.

stat/lstat is already protected by a `LSTAT` define you can add to your build environment.

**Comment by vapier** [comment]
the code uses `BYTEORDER` rather than `BYTE_ORDER`, but why do you need to define that at all ?  if it's not defined (the default), then the code fallsback to generic code that works regardless of endian.  do you really need it ?  what build failures are you seeing w/out it defined ?

**Comment by deguich** [comment]
Hi, I used the master compress.c version where lstat is not protected and BYTEORDER is 0000.
I didn't see compress42.c in branch 4.2.4.

**Comment by vapier** [comment]
avoid master for now

**Comment by vapier** [comment]
prob fixed now
