### ISSUE TITLE
Makefile should respect PREFIX

### ISSUE THREAD

**Issue by eli-schwartz** [vapier/ncompress#23]
This already exists on the (abandoned?) master branch, but not in the branch that is actually getting maintenance releases. It would be beneficial for packaging purposes to make this available for practical use.

While I am at it, I think it would also be nice to have the install_extra logic. (If the install target needs to continue to install everything for compatibility purposes, it could be split into e.g. `make install_core install_extra`?)

**Comment by vapier** [comment]
feel free to send PRs
