### ISSUE TITLE
compress42.c:707]: (style) Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [vapier/ncompress#8]
Source code is

     if ((fgnd_flag = (signal(SIGINT, SIG_IGN)) != SIG_IGN))

Maybe better code

    if ((fgnd_flag = signal(SIGINT, SIG_IGN)) != SIG_IGN)

**Comment by vapier** [comment]
i agree the code isn't exactly clear, or perhaps that common in current style practices, but the code as-written is correct.  `fgnd_flag` is a flag variable and is described earlier:

```c
int             fgnd_flag = 0;      /* Running in background (SIGINT=SIGIGN)        */
```

it is *not* holding the previous signal disposition.
